name: Building kernel

on: # [push]
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      COMPILER:
        description: 'compilers used'
        required: true
        default: 'shattered-Clang-15'
      KREPO:
        description: 'kernel repo'
        required: true
        default: 'https://github.com/vildangil/BlackSide_NEW_kernel_xiaomi_blossom'
      KBRANCH:
        description: 'kernel branch'
        required: true
        default: 'infinity'
      NOTES:
        description: 'notes to print out'
        required: false
        default: ''
      SUFFIX:
        description: 'suffix to aplly to teh zip filename'
        required: false
        default: ''
      ZREPO:
        description: 'zipper repo'
        required: false
        default: 'https://github.com/vildangil/BlackSide_Kernel_Blossom_AnyKernel3'
      ZBRANCH:
        description: 'zipper branch'
        required: false
        default: 'main'
      KSU:
        description: 'if dont want ksu then leave blank'
        required: false
        default: ''
      TG_RECIPENT:
        description: 'group id'
        required: false
        default: '-1002271811805'
      CONTAINER:
        description: 'if you know you know'
        required: true
        default: 'fedora:40'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.CONTAINER }}
    steps:
        - name: checkout builder
          uses: actions/checkout@v4
        - name: setup environment
          run: |
            echo "WORKFLOW_START=$(date +%s)" >> $GITHUB_ENV
            echo "COMPILERS=${{ github.event.inputs.COMPILER }}" >> $GITHUB_ENV
            echo "KREPO=${{ github.event.inputs.KREPO }}" >> $GITHUB_ENV
            echo "KBRANCH=${{ github.event.inputs.KBRANCH }}" >> $GITHUB_ENV
            echo "NOTES=${{ github.event.inputs.NOTES }}" >> $GITHUB_ENV
            echo "SUFFIX=${{ github.event.inputs.SUFFIX }}" >> $GITHUB_ENV
            echo "ZREPO=${{ github.event.inputs.ZREPO }}" >> $GITHUB_ENV
            echo "ZBRANCH=${{ github.event.inputs.ZBRANCH }}" >> $GITHUB_ENV
            echo "KSU=${{ github.event.inputs.KSU }}" >> $GITHUB_ENV
            echo "TG_RECIPENT=${{ github.event.inputs.TG_RECIPENT }}" >> $GITHUB_ENV
            echo "RUN_NUM=${{ github.run_id }}_${{ github.run_attempt }}" >> $GITHUB_ENV
            
        - name: clone kernel
          run: |
            git clone --depth=1 $KREPO -b $KBRANCH kernel
            
        - name: Patching ksu & compilation
          run: |
            cd kernel
            case "${{ github.event.inputs.KSU }}" in
              "" )
                bash ../tg_utils.sh msg "gh $RUN_NUM: KernelSU patching disabled, normal build"
                bash ../tg_utils.sh msg "gh $RUN_NUM: running compilation script(s): $COMPILERS"
                bash ../build.sh "$COMPILERS"
              ;;
              * )
                bash ../tg_utils.sh msg "gh $RUN_NUM: KernelSU patching enabled, patching"
                # МЕНЯЕМ ТОЛЬКО ЭТУ СТРОКУ: вызываем твой asus.sh вместо applyPatches.sh
                bash ../asus.sh " "
                bash ../tg_utils.sh msg "gh $RUN_NUM: running compilation script(s): $COMPILERS"
                bash ../build.sh "$COMPILERS"
              ;;
            esac

        - name: upload
          run: |
            cd kernel
            if [[ $(ls *.zip) ]]; then
              for file in *.zip ; do
                bash ../tg_utils.sh up "${file}" "$(cat "${file}.info")"
              done
            fi
            if [[ $(ls *.log) ]]; then
              for file in *.log ; do
                if [ -e "${file}.info" ]; then
                  bash ../tg_utils.sh up "${file}" "$(cat "${file}.info")"
                fi
              done
            fi
            
        - name: if it fails
          if: ${{ failure() }}
          run: |
            WORKFLOW_END=$(date +"%s")
            WDIFF=$((WORKFLOW_END - WORKFLOW_START))
            bash tg_utils.sh msg "gh $RUN_NUM: workflow failed in $((WDIFF / 60))m, $((WDIFF % 60))s"

        - name: end of workflow
          run: |
            WORKFLOW_END=$(date +"%s")
            WDIFF=$((WORKFLOW_END - WORKFLOW_START))
            bash tg_utils.sh msg "gh $RUN_NUM: workflow ended in $((WDIFF / 60))m, $((WDIFF % 60))s"
